### ISSUE TITLE
设置背景色badgeBgColor漏掉了、设置badgeRadius没有效果

### ISSUE THREAD

**Issue by maltsugar** [RylanJIN/RJBadgeKit#10]
感谢作者提供很好的思路，提两个建议
1. badgeBgColor 代码写了，没有暴露在协议里
2. 设置badgeRadius没有效果，使用了默认值

希望作者有空更新下

**Comment by rjinxx** [comment]
感谢提出，0.2.1已修复，谢谢！

**Comment by maltsugar** [comment]
设置badgeRadius还是有问题啊，你没改frame ，宽高还是用CGFloat width = kRJBadgeDefaultRadius * 2;
再改badgeRadius 就不是圆形的。
badgeRadius这个应该理解为小红点的半径

**Comment by maltsugar** [comment]
加了两行代码，提了个pull request ，测试没有问题
