### ISSUE TITLE
父节点消息被清除的回调

### ISSUE THREAD

**Issue by CNDEVE** [RylanJIN/RJBadgeKit#19]
你好，如果一个父节点A管理B和C，当B和C都被点击查看了之后，A的红点会被清除，这时候我能监听到A节点被清除吗，badge不是数值模式，我该怎么监听到父节点A红点被清除了呢？

**Comment by rjinxx** [comment]
可以直接监控父节点的路径，然后在回调里面查看RJBadgeShowKey的value是否为NO来判断当前是否被清除了，具体可以看demo工程RJViewController里面第43行

**Comment by CNDEVE** [comment]
好的  谢谢
