### ISSUE TITLE
还有种是策略问题

### ISSUE THREAD

**Issue by Xiangao2018** [RylanJIN/RJBadgeKit#2]
实际上策略有很多种，常见数字、小红点、new

这个策略实际上是应该由使用者来提供

如果存在数字 小红点、new  哪种优先？

**Comment by rjinxx** [comment]
我博文里面有说明这个优先级考虑的:

【既然可以展示三种样式的小红点UI, 那么就需要有一个优先级排序，结合上面的setBadge接口, 我们可以想到的规则是如果setBadge时没有设置count, 那么默认就是展示小红点, 如果设置了count, 那么就展示数字。另外在展示小红点的情况下，如果用户设置了自定义icon那么就优先展示icon, 按照这个思路，小红点样式的优先级就出来了: 数字的优先级最高，其次是自定义icon, 最后则是默认的圆形小红点。】

所以优先级是: 数字 >  new > 小红点
