### ISSUE TITLE
初始化默认有小红点吗?

### ISSUE THREAD

**Issue by miniLV** [RylanJIN/RJBadgeKit#20]
```
info= {
    RJBadgeCountKey = 0;
    RJBadgePathKey = "root.miniLV.page";
    RJBadgeShowKey = 1;
}
```

子节点的节点上，红点的数量都为0，但是 RJBadgeShowKey = 1导致 根节点上的控件有红点提示.

测试修改
```
@{RJBadgeNameKey : @"root",
                                                    RJBadgePathKey : @"root",
                                                    RJBadgeCountKey: @(0),
                                                    RJBadgeShowKey : @(NO)};
初始化 - RJBadgeShowKey 设置为NO，最后的info信息里面还是YES，请问是我哪里设置出了问题了吗
```

**Comment by rjinxx** [comment]
清除小红点是针对路径来操作的，使用下面的函数来清除path对应的红点:
`[RJBadgeController clearBadgeForKeyPath:xxx]`
如果该路径下还有子路径，则清除所有子路径后，父路径的红点自动清除。如果需求强制清除父路径的红点可以用下面的函数然后把force设为YES:
`[RJBadgeController clearBadgeForKeyPath:xxx forced:YES]`

**Comment by miniLV** [comment]
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{

    //cell - 点击清除当前路径
    [RJBadgeController clearBadgeForKeyPath:_itemPathKVOList[indexPath.row]];
}

我在子路径里面做此操作，清空完毕之后，回到rooter节点VC，再进入 子路径VC，此时子路径的红点已经在之前的操作下被清空完毕了，log表面也是子节点下没有value，开始回到rootVC，rooterVC的按钮上有红点显示，log info 得到：`info= {
    RJBadgeCountKey = 0;
    RJBadgePathKey = "root.miniLV.page";
    RJBadgeShowKey = 1;
}`，如果有办法 设置 `RJBadgeShowKey 初始化 = 0`，我猜测可能有办法解决，但是无论我如何设置，存储到plist中的数据，以及init的dict的 RJBadgeShowKey 始终 = true
我描述得够清楚吗-。-还是需要demo~， 很急需要帮忙~

**Comment by rjinxx** [comment]
你写个demo给我吧，我帮你看下

**Comment by miniLV** [comment]
Demo - `https://github.com/miniLV/RJBadgeKitDemo`

场景 - 第一次进入有数据，把小红点全部点击 - 清空之后
第二次进入，默认子节点已经没有数据了 - 根节点还是有红点，demo如上

**Comment by rjinxx** [comment]
Hi 我看了代码，这边有两个问题，首先是红点有两个模式，一个是显示默认的红点，一个是红点上带数字，称为数字模式。如果直接用setBadgeForKeyPath会显示默认红点，对应info里面RJBadgeShowKey为1，这个情况下RJBadgeCountKey（指红点上显示的数值）就为0了，但这时红点是开启/显示状态的，如果用setBadgeForKeyPath:count函数，就会显示红点并且上面还会带数值。然后第二个问题是你在viewDidLoad里面调用p_addRedpointKVO，这个里面直接调用setBadgeForKeyPath会直接触发显示默认的小红点（不带数值的），所以第二次再进入，由于你已经设置了setBadgeForKeyPath,所以这时红点是开启状态的，至于你没看到红点显示是因为你把显示红点的设置[self.badgeController observePath:_itemPathKVOList[indexPath.row] badgeView:cell.textLabel block:nil]放到cellForRowAtIndexPath了，你可以试试把这个设置放到viewDidLoad, 你就会看到进来后红点已经开启并且显示了。

**Comment by miniLV** [comment]
那如果是demo中的示例，我的需求是，根页面只显示有无红点，子节点在显示具体的数字，并且，具体的数字是根据网络请求-数据源获取到，并设置在tableViewCell上的话，用该`RJBadgeKi`库有办法实现吗，或者你能不能在我 demo 的基础之上稍作修改，因为 ```显示红的设置[self.badgeController observePath:_itemPathKVOList[indexPath.row] badgeView:cell.textLabel block:nil]``` 是再tableViewCell上设置，所以我具体不清楚要怎么抽到viewDidLoad里

**Comment by KinmoCode** [comment]
怎么设置在cell上面
