### ISSUE TITLE
root 路径下可以不显示 子节点 count之和吗

### ISSUE THREAD

**Issue by miniLV** [RylanJIN/RJBadgeKit#22]
root节点 - root.miniLV.page

两个子节点
NSString * const RJItemPath1 = @"root.miniLV.page.item1";
NSString * const RJItemPath2 = @"root.miniLV.page.item2";

root 节点，只想显示默认的红点状态，`[RJBadgeController setBadgeForKeyPath:path count:1];`即便我在 Root 上设置，count 始终 == 1，或者 == 0，计算的法则都是  RJItemPath1.count + RJItemPath2.count，有办法让 root节点如果有值默认只显示一个小红点吗

- 目前Root中的代码，不管是`[RJBadgeController setBadgeForKeyPath:path];` - 没设置count
- 强制设置数量 - `[RJBadgeController setBadgeForKeyPath:path count:0];` or `[RJBadgeController setBadgeForKeyPath:path count:1];`都无法实现效果

展示数字的优先级比较高，这个有办法自己控制吗

![image](https://user-images.githubusercontent.com/20677007/47057742-95c8f280-d1f4-11e8-83b1-916a756d1b51.png)
  ##需要类似这种，root层始终只显示红点(有值的情况)，有办法实现吗

**Comment by miniLV** [comment]
补充 ：
根节点需要显示count - 使用 
`[RJBadgeController setBadgeForKeyPath:_itemPathKVOList[indexPath.row] count:model.contentNum];`

root节点只希望显示红点 - `[RJBadgeController setBadgeForKeyPath:rootPath];`

在排除子节点使用`[RJBadgeController setBadgeForKeyPath:_itemPathKVOList[indexPath.row]];`不设置 count ，不显示 count数量的前提下，有办法实现吗

**Comment by rjinxx** [comment]
目前是默认父节点显示和子节点的样式一致，而且在有子节点的情况下，设置父节点的count是无效的，父节点的count是子节点的count之和。如果有子节点的情况下，再让单独设置父节点那就乱了，所以父节点都是自动计算出来的。

你这个情况可以单独再设置一个路径对应外面那个目录，然后当里面的子路径（或者直接监测父路径）show badge为YES的情况下，设下外面那个路径的set badge
