### ISSUE TITLE
请问UITabBarItem和UIBarButtonItem为什么不重写customView的set和get方法呢

### ISSUE THREAD

**Issue by yyyzzq** [RylanJIN/RJBadgeKit#7]

**Comment by rjinxx** [comment]
没有get到你的point, 可以把你的问题再说具体一点吗？

**Comment by yyyzzq** [comment]
UITabBarItem+RJBadge这个分类中重写了RJBadgeView这个协议的方法，但是@optional的两个方法没有重写，我就是不太懂为什么不重写，如果不重写的话那是不是就不能使用customView和badgeImage了

**Comment by rjinxx** [comment]
这个遗漏了，我后面加上，感谢提出。
