### ISSUE TITLE
小红点跑偏了，在默认情况下

### ISSUE THREAD

**Issue by kthree0830** [RylanJIN/RJBadgeKit#8]
![wx20180305-103443](https://user-images.githubusercontent.com/13103920/36955030-d9ca4e8e-2060-11e8-8ce2-2ac74cb1273f.png)
小红点跑偏了，在默认情况下

**Comment by rjinxx** [comment]
你是直接加在cell上了么，还是加在icon imageView上的？

**Comment by kthree0830** [comment]
imageview上的,3月2号pod的版本没有refreshBadgeView这个方法,启动后不掉用setBadgeForKeyPath,也会显示红点

**Comment by rjinxx** [comment]
是cell复用引起的，你可以在endDisplayCell的回调中unObservePath, 然后在willDisPlayCell的时候重新addObservePath或者每次cellForItemAtIndexPath重新configCell/Data的时候直接把UIImageView删除后重新关联对应的path后new一个
