### ISSUE TITLE
有个小问题，如果在某些场景，希望修改小红点的颜色或者数字色，应该怎么修改？

### ISSUE THREAD

**Issue by szmichaelyb** [RylanJIN/RJBadgeKit#9]
RJBadgeKit是一个不错的解决方案，但还是有个小问题，需要请教一下
想问一下，如果在某些场景，希望修改小红点的颜色或者数字颜色，应该怎么修改？

比如：有一个场景，导航栏颜色为红色，导航栏item的badge显示数字。
此时，如果badge的背景色显示为红色，总感觉不是很好看，有点看不清。

希望修改bandge的背景色为白色或者其他颜色（非红色就行），文字色改成白色。

我试过，设置customView，貌似没有啥效果。。。。

![image](https://user-images.githubusercontent.com/9857312/38408416-045d84b4-39b0-11e8-84ba-499eea83232d.png)

**Comment by JustinInCoding** [comment]
try 
`msgBtn.badge.backgroundColor = [UIColor redColor]; msgBtn..badge.textColor = ...` @Michaelyb520

**Comment by maltsugar** [comment]
设置按钮好像可以  
设置tabBarItem.badge.backgroundColor = [UIColor orangeColor];不行

**Comment by rjinxx** [comment]
0.2.1已修复, 可以这样设置:
```
button.badgeRadius  = 5;
button.badgeBgColor = [UIColor blueColor];
```
